# fly.toml app configuration file generated for mmbw-api on 2023-08-11T14:30:21+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mmbw-api"
primary_region = "jnb"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
